---
before_install:
  - "git fetch --tags"
  - "export PATH=${PATH}:./vendor/bundle"

scala_212: &scala_212 2.12.10
scala_213: &scala_213 2.13.0

language: scala
services:
  - postgresql

cache:
  directories:
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./website/build/http4s-modules
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  true:
    branch: master
dist: xenial
install:
  - "rvm use 2.3.0 --install --fuzzy"
  - "gem update --system"
  - "gem install sass"

stages:
  - name: styling
  - name: test
  - name: release
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
    - &all_tests
      stage: test
      env: TEST="all_tests"
      script: ./all_tests.sh
      scala: *scala_212
    - <<: *all_tests
      env: TEST="all_tests"
      scala: *scala_213
    - env: TEST="docs"
      script: ./script/travis_init.sh && sbt ++$TRAVIS_SCALA_VERSION docsJVM/mdoc && sbt ++$TRAVIS_SCALA_VERSION docsJVM/docusaurusCreateSite
      scala: *scala_212
    - stage: styling
      env: TEST="styling"
      scala: *scala_213
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
    - stage: release
      script: sbt ci-release
