dist: xenial

services:
  - postgresql

language: scala

scala:
   - 2.12.10
   - 2.13.0

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass

before_script:
  ./script/travis_init.sh
  npm i -g npm@8
  npm i -g yarn gulp-cli

script: sbt ++$TRAVIS_SCALA_VERSION jvm:test

jobs:
  include:
    - script:
      - sbt docs/mdoc
      - sbt docs/docusaurusCreateSite
      if: TRAVIS_SCALA_VERSION == "2.12.10"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./website/build/http4s-modules
  target-branch: gh-pages
  on:
    branch: master


cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"