--- 
before_install: 
  - "git fetch --tags"
  - "export PATH=${PATH}:./vendor/bundle"
cache: 
  directories: 
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
deploy: 
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./website/build/http4s-modules
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  true: 
    branch: master
dist: xenial
install: 
  - "rvm use 2.3.0 --install --fuzzy"
  - "gem update --system"
  - "gem install sass"
jobs: 
  include: 
    - 
      name: Init
      script: 
        - ./script/travis_init.sh
        - "npm i -g yarn gulp-cli"
        - "sbt exampleServerJVM/stage"
      stage: Tests
    - 
      script: 
        - "echo \"Starting integration test script\""
        - ./all_tests.sh
    - 
      stage: Docs
    - 
      if: "TRAVIS_SCALA_VERSION == \"2.12.10\""
      script: 
        - "sbt docs/mdoc"
        - "sbt docs/docusaurusCreateSite"
    - 
      script: "sbt ci-release"
      stage: Release
language: scala
scala: 
  - "2.12.10"
  - "2.13.0"
services: 
  - postgresql
stages: 
  - init
  - test
  - docs
  -
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"
    name: release
