dist: xenial

services:
  - postgresql

language: scala

scala:
   - 2.12.8

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

before_script:
  ./script/travis_init.sh

jobs:
  include:
    - stage: verify

      script:
        - sbt test
        - sbt docs/mdoc
        - sbt docs/makeMicrosite
        - mkdir -p ./site
        - cp -R h4sm-docs/target/site/* ./site/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./site
  target-branch: gh-pages
  on:
    branch: master
