name: Http4s Modules
baseurl: /http4s-modules
description: Documenting uses of H4SM
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.26
org: com.clovellytech
markdown: kramdown
